### ISSUE TITLE
Head and HTML Tags Should Not Be Inline With The <!DOCTYPE html> Declaration

### ISSUE THREAD

**Issue by robynmaya** [FinnFess/prj-rev-bwfs-tea-cozy#2]
https://github.com/FinnFess/prj-rev-bwfs-tea-cozy/blob/3e3de6ee69edd6190a8be8536f7b43fd13f2722c/Project%202/index.html#L2

The <html> and <head> tags should not be inline with the <!DOCTYPE html> declaration. In fact, these three should be on its own line, like so :  

```
<!DOCTYPE html>
<html>
<head>
</head>

<body>
</body>

</html>
```

**Comment by FinnFess** [comment]
Didnt know that.. thanks!
