### ISSUE TITLE
Where Are Your Meta Tags?

### ISSUE THREAD

**Issue by robynmaya** [FinnFess/prj-rev-bwfs-tea-cozy#4]
https://github.com/FinnFess/prj-rev-bwfs-tea-cozy/blob/3e3de6ee69edd6190a8be8536f7b43fd13f2722c/Project%202/index.html#L5

It will be better if you also include Meta tags in your element, for example :

```
<meta charset="UTF-8">
<meta name="description" content="Tea Cozy - Portland's Best Tea Provider">
<meta name="keywords" content="Tea, Portland, Best Cafe">
<meta name="author" content=“John Doe">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

A description will appear on search engine as a brief description of your page, although it may or may not affect your page/site ranking, but it is a good practice still - at least, a compelling description can entice more visitors to come to your site.

A viewport element gives the browser instructions on how to control the page's dimensions and scaling.

The width=device-width part sets the width of the page to follow the screen-width of the device (which will vary depending on the device).

The initial-scale=1.0 part sets the initial zoom level when the page is first loaded by the browser.
Read more

[Meta Tags](https://moz.com/blog/seo-meta-tags)

**Comment by FinnFess** [comment]
Ill include them next time
