### ISSUE TITLE
Local Files Exist But You Use Online Resources?

### ISSUE THREAD

**Issue by robynmaya** [FinnFess/prj-rev-bwfs-tea-cozy#5]
https://github.com/FinnFess/prj-rev-bwfs-tea-cozy/blob/3e3de6ee69edd6190a8be8536f7b43fd13f2722c/Project%202/index.html#L12

I noticed you uploaded your sources for images, did you actually intend to use them or would you like to use online resources for your images - like what you did so far. 

Either way could work just fine; but using your own local files, will help safeguarding your assets in case the host/server of your external images goes down or remove the content.

**Comment by FinnFess** [comment]
Okay i will store them locally
