### ISSUE TITLE
Good Job On Using an HTML5 Semantic Element 

### ISSUE THREAD

**Issue by robynmaya** [FinnFess/prj-rev-bwfs-tea-cozy#6]
https://github.com/FinnFess/prj-rev-bwfs-tea-cozy/blob/3e3de6ee69edd6190a8be8536f7b43fd13f2722c/Project%202/index.html#L13-L17

Good job on using <nav> to group your navigation section. Using HTML5 Semantic elements is considered a good practice for a blog-like webpage. 

Try using the `<article></article>` element in place of your `div`s that group the content.

[HTML5 Elements](https://codepen.io/mi-lee/post/an-overview-of-html5-semantics)

**Comment by FinnFess** [comment]
Will do that :)
