### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by robynmaya** [FinnFess/prj-rev-bwfs-tea-cozy#7]
Grade : Needs Improvement

You did almost perfect, but we could not grade you properly due to the missing CSS file. 

You did good in naming your id name to be unique and specific, and your class names to be more generic but still descriptive. 

Recommendation : 

- Including Meta tags in your `<head></head>`element. 

- Don't use heading elements for information that is not intended to be the title of some sub-content. In your index.html, you used `<h5></h5>` element to encapsulate your 'copyright' information, but `<p></p> `element is more appropriate in this case. 

- Last but not least, be consistent with your asset resources, if you were going to use online resources for your images, you don't need to include them in your project folder. But ideally, using local assets is better and they are all also supposed to be inside one asset folder.

**Comment by FinnFess** [comment]
Thanks for the Feedback! I forgot to upload the CSS file.. will do that better next time! Have a nice day :)

**Comment by robynmaya** [comment]
Great work, FinnFess!! Looking forward to see more of your work! 👍
